### ISSUE TITLE
Promote Live Stream

### ISSUE THREAD

**Issue by surma** [WebAssemblySummit/webassembly-summit.org#113]
The live stream URL is now available:

https://youtu.be/WZp0sPDvWfw

We should probably put it on the front page at some point.

**Comment by torch2424** [comment]
@surma Totally! I can open a quick PR for this Sunday? :smile:

**Comment by ttraenkler** [comment]
cool, wdyt maybe we could reuse the removed apply buttons for the livestream? 
as a second button we could use the discord link to facilitate exchange

**Comment by torch2424** [comment]
@ttraenkler 

> maybe we could reuse the removed apply buttons for the livestream?

I am unsure what the apply buttons are? :thinking: 

> as a second button we could use the discord link to facilitate exchange

I am also unsure what you mean by this? Maybe replace the discord button with the Youtube link? Or share the Youtube link on Discord? :smile: 

But if anything, since the event is tommorrow, in a couple of hours I'll open a PR and then we can discuss if something is wrong on that :joy: Thanks for the feedback by the way! :smile: :+1:

**Comment by ttraenkler** [comment]
@torch2424 the buttons on the landing page we had to apply for tickets or as speaker. up to you i just thought this might be the quickest

**Comment by torch2424** [comment]
Ohhhhhh! Like apply to the conference. I know what you mean now haha! :joy: Totally! Will do that now. Definitely would be the quickest :smile:
