### ISSUE TITLE
Add FAQ?

### ISSUE THREAD

**Issue by surma** [WebAssemblySummit/webassembly-summit.org#24]
- Is this a community event?
- Who is organizing?
- Who can I contact?
- Will it be livestreamed?
- Will the talks be recorded
- ... (add more!)

**Comment by pranjal9599** [comment]
Yeah we should definitely add this

**Comment by pranjal9599** [comment]
Thoughts on adding a page like this https://rustconf.com/about/#faqs and adding faqs there?

**Comment by ashleygwilliams** [comment]
sounds good to me @pranjal9599 !

**Comment by torch2424** [comment]
Agreed, LGTM @pranjal9599 😄 👍

**Comment by pranjal9599** [comment]
Hi this is my proposal for about page i think we can add organizers #29  here as well along with faqs and any other info 


<img width="1659" alt="image" src="https://user-images.githubusercontent.com/15066223/70390475-65907480-19f1-11ea-9d22-0a932bc45304.png">
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/15066223/70390480-6d501900-19f1-11ea-9d1e-4ea295c773d3.png">

**Comment by pranjal9599** [comment]
Opened a pr need to update content though

**Comment by ttraenkler** [comment]
@pranjal9599 Thanks for the proposal!

We've separated the FAQ content from the design in #31 so until this is finalised we can already publish a markdown version of the FAQ like for the code of conduct since the application deadline is already in two days. 

With regard to the design draft, I think with respect to the deadline it would be easier if we first focus on the pure FAQ and deal with the organiser and overall design after this. Could you make a PR without the header and the organizer cats and open a separate issue for this so we can already merge the FAQ?

**Comment by pranjal9599** [comment]
@ttraenkler Edited the existing pr now it only contains faqs from markdown

<img width="1590" alt="image" src="https://user-images.githubusercontent.com/15066223/70504943-ce403400-1b4c-11ea-8cf6-67d27e935f3f.png">
<img width="1590" alt="image" src="https://user-images.githubusercontent.com/15066223/70504955-d5674200-1b4c-11ea-885e-ebfdd4d4ca69.png">

**Comment by ttraenkler** [comment]
@torch2424 @ashleygwilliams From my side this version is solid enough to be merged already with respect to the deadline. I've talked to @pranjal9599 and he's cool if I give it a polish. If welcome I will give it a polish later, but imho it's more important to have this info published now. Please approve and merge if you agree.

**Comment by ttraenkler** [comment]
I've merged @pranjal9599 s PR. The organizer header will be dealt with in #29 so, this issue is closed.
